# Generated by Django 5.2.8 on 2025-11-29 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email_id', models.EmailField(max_length=254)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
